FROM golang:1.18

RUN export GO111MODULE="on"

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY . /app

RUN go mod download

ENTRYPOINT CompileDaemon -polling --build="go build query/main_query.go" --command=./main_query